log_recorder:
  - source: "C:/TempA"
  - destination: "c:/dest"
  - interval: "2"
  - extension: "*.*"

log_writer:
  - destination: "C:/TempA"
  - interval: "2"
  - filename: "log_writer.txt"

screen_recorder:
  - frame_per_second: 20
  - filename: 'screen_recorder_out.avi'
  - codec: 'XVID'

get_remote_files_config:
  - ip: "127.0.0.1"
  - port: 22
  - username: "Me"
  - password: ""

remote_api_config:
  - ip: "127.0.0.1"
  - port: 9000